### ISSUE TITLE
Internal load balancer not accurate?

### ISSUE THREAD

**Issue by fsimonazzi** [palma21/secureaks#2]
The diagram of the secure version shows the app gateway connecting to an internal load balancer which exposes pods. But my understanding with AGIC is that the app gateway connects directly to the pods (it sets up the individual pods IP addresses as entries in the corresponding host pool). Is this correct?

**Comment by fsimonazzi** [comment]
Also section https://github.com/palma21/secureaks#service-segregation-with-network-policies states "NOTE: The 10.42.2.232 IP Address below is the IP Address of the Internal Load Balancer (ILB) created above when Ingress was being setup."

The Internal Load Balancer is created _for the webapp service_, not the ingress, https://github.com/palma21/secureaks/blob/master/web.yaml#L34-L45 (and it wouldn't be used by the ingress as stated earlier)

**Comment by palma21** [comment]
Yeah the diagram leaves quite a bit to be desired, I'll try to work to improve it.

You're correct App GW connects directly to pods.

ILB is an example for an internal path (not web facing) and is actually an optional piece.
