### ISSUE TITLE
Very secure indeed ;-)

### ISSUE THREAD

**Issue by mkosieradzki** [palma21/secureaks#9]
This is indeed very secure ;-) LOL

`az network firewall network-rule create -g $RG -f $FWNAME --collection-name 'aksfwnr' -n 'netrules' --protocols 'TCP' --source-addresses '*' --destination-addresses '13.0.0.0/8' '20.0.0.0/8' '23.0.0.0/8' '40.0.0.0/8' '51.0.0.0/8' '52.0.0.0/8' '65.0.0.0/8' '70.0.0.0/8' '104.0.0.0/8' '131.0.0.0/8' '157.0.0.0/8' '168.0.0.0/24' '191.0.0.0/8' '199.0.0.0/8' '207.0.0.0/8' '209.0.0.0/8' --destination-ports 9000 22 443 53 445 --action allow --priority 100`

**Comment by mkosieradzki** [comment]
`az network firewall application-rule create -g $RG -f $FWNAME --collection-name 'aksfwar' -n 'fqdn' --source-addresses '*' --protocols 'http=80' 'https=443' --target-fqdns "${ACR_NAME}.azurecr.io" '*.azmk8s.io' 'aksrepos.azurecr.io' '*blob.core.windows.net' '*mcr.microsoft.com' '*.cdn.mscr.io' 'login.microsoftonline.com' 'management.azure.com' '*ubuntu.com' --action allow --priority 100`

Those entries:
- `*.azmk8s.io`
- `*blob.core.windows.net
are also not very secure...

The lack of dot here: `'*ubuntu.com'` is just a mistake, as attacker can just create `myubuntu.com` domain and it will pass...

**Comment by palma21** [comment]
This was an example to support a conference talk. There are more issues than those :)

For reference on outbound security please check https://aka.ms/aks/egress
